events { worker_connections 1024; }
http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    client_max_body_size 500M;
    location / {
      try_files $uri $uri/ /index.html;
    }
    location /roms/ {
      add_header 'Access-Control-Allow-Origin' '*';
      add_header 'Cross-Origin-Resource-Policy' 'cross-origin';
    }
  }
}
